using UnityEngine;

public class Player : MonoBehaviour
{
    private StateMachine stateMachine;

    public Player_IdleState idleState { get; private set; }

    public Player_MoveState moveState { get; private set; }
    private void Awake()
    {
        stateMachine = new StateMachine();

        idleState = new Player_IdleState(this,stateMachine, "idle");
        moveState = new Player_MoveState(this,stateMachine, "move");

    }

     private void Start()
    {
        stateMachine.Initialize(idleState);
    }

    private void Update()
    {
        
        stateMachine.currentState.Update();
    }
}
